title: Yucai Bai
url: "https://raymondbyc.github.io"
baseurl: ""

markdown: kramdown
#ins_logo: "./bits-logo.png"

tracking_id: G-P8KTMD4X17

footer: yes
footer_url: "https://github.com/raymondbyc"
footer_text: "Welcome to my blog"

sass:
    style: compressed
    sass_dir: _sass

nav:
 - name: "About"
   link: "https://raymondbyc.github.io/"
 - name: "Resume"
   link: "resume.pdf"
 - name: "Contact"
   link: "contact"
