title: Yucai Bai
url: "https://raymondbyc.github.io"
baseurl: ""

markdown: kramdown
#ins_logo: "./bits-logo.png"

tracking_id: UA-148972084-1

footer: yes
footer_url: "https://github.com/raymondbyc"
footer_text: "Welcome to my blog"

sass:
    style: compressed
    sass_dir: _sass

nav:
 - name: "Transcripts"
   link: "Transcripts.pdf"
 - name: "Curriculum Vitae"
   link: "curriculum vitae.pdf"
 - name: "Resume_ZH"
   link: "resume_zh.pdf"

